### ISSUE TITLE
Add note taking app supporting markdown

### ISSUE THREAD

**Issue by fazlearefin** [fazlearefin/ubuntu-dev-machine-setup#11]
Probably will go with boostnote, because of the popularity and the github stars:

- ~[boostnote](https://github.com/BoostIO/Boostnote)~
- [ghostwriter](https://github.com/wereturtle/ghostwriter)
- [Standard Notes](https://standardnotes.org/)
- [Notes-up](https://github.com/Philip-Scott/Notes-up)
- [Quilter](https://github.com/lainsce/quilter)
- [Zettlr](https://github.com/Zettlr/Zettlr)
- [Joplin](https://joplinapp.org/) - Great but uses its own directory and own format for storage
- [Notable](https://github.com/notable/notable) - Excellent but is still close-sourced
- ~[Mark Text](https://marktext.app/) - Excellent but has no vim keybindings~ Domain up for sale

**Comment by fazlearefin** [comment]
- [Standard Notes](https://standardnotes.org/)
- [Notes-up](https://github.com/Philip-Scott/Notes-up)
- [Quilter](https://github.com/lainsce/quilter)

**Comment by fazlearefin** [comment]
`ghostwriter` added in 6de2a5f6900f07633b3a0fb4022797088ec5cdcc
This is good for viewing and editing single page markdown files

**Comment by fazlearefin** [comment]
Boostnote has started using json format in their recent version. This makes it difficult to export notes using tools independent of Boostnote.

**Comment by fazlearefin** [comment]
[Obsidian](https://obsidian.md/) is an excellent app but it is closed sourced.

**Comment by fazlearefin** [comment]
**Obsidian** has been chosen over **Zettlr** for vim mode editing support. Zettlr would have been chosen if they supported vim mode alongside normal and emacs mode.

Code to install Obsidian will be added shortly (by end of 2021)

**Comment by fazlearefin** [comment]
Easier option is to install using flatpak

**Comment by sven-frotscher** [comment]
Other options:
* https://github.com/fabiocolacio/Marker (Flathub or PPA)
* https://apps.gnome.org/de/Apostrophe (GNOME's counterpart to ghostwriter; available on Flathub or, from 23.04 onwards, in Ubuntu's `universe` repo)

**Comment by fazlearefin** [comment]
[apostrophe](https://gitlab.gnome.org/World/apostrophe) is in the ubuntu 24.04 ubuntu repo!

```console
root@dac7e7fdc6b9:~# apt search apostrophe
Sorting... Done
Full Text Search... Done
apostrophe/noble 2.6.3-4 amd64
  Distraction free Markdown editor

root@dac7e7fdc6b9:~# apt show apostrophe
Package: apostrophe
Version: 2.6.3-4
Priority: optional
Section: universe/gnome
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 3465 kB
Depends: dconf-gsettings-backend | gsettings-backend, python3:any, python3-pypandoc, gir1.2-gspell-1, gir1.2-handy-1, gir1.2-glib-2.0, gir1.2-gtk-3.0, gir1.2-webkit2-4.1
Homepage: https://gitlab.gnome.org/World/apostrophe
Download-Size: 2577 kB
APT-Sources: http://archive.ubuntu.com/ubuntu noble/universe amd64 Packages
Description: Distraction free Markdown editor

root@dac7e7fdc6b9:~#
```

**Comment by fazlearefin** [comment]
Ghostwriter replaced with apostrophe in https://github.com/fazlearefin/ubuntu-dev-machine-setup/commit/78651b296120a02d763ce47cb11a62fdbf8ffac5

**Comment by fazlearefin** [comment]
Latest version of obsidian also installed in https://github.com/fazlearefin/ubuntu-dev-machine-setup/commit/193c28a9accf080f8acb48a07222206e726ec943
